version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/coursevault/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=LAgr4XhIf6p2M64phoVYPxOzSSJPM4Pz
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password123